import {
  Modal,
  Stack,
  Group,
  Button,
  TextInput,
  Radio,
  Breadcrumbs,
  Anchor,
  Badge,
  Text,
  Alert,
  Loader,
  ActionIcon,
  Paper,
} from '@mantine/core'
import {
  IconFolder,
  IconFile,
  IconArrowUp,
  IconAlertCircle,
  IconShare,
} from '@tabler/icons-react'
import { useState, useEffect, useCallback } from 'react'

import { useCloudStorage } from '../../contexts/CloudStorageContext'
import { syncService } from '../../services/syncService'

import type {
  FileInfo,
  FolderInfo,
} from '../../utils/storage/ICloudStorageProvider'

interface FileSelectionModalProps {
  opened: boolean
  onClose: () => void
  onSelectFile: (fileInfo: FileInfo) => void
}

interface BreadcrumbItem {
  label: string
  path?: string
}

export function FileSelectionModal({
  opened,
  onClose,
  onSelectFile,
}: FileSelectionModalProps) {
  const cloudStorage = useCloudStorage()

  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [currentFolder, setCurrentFolder] = useState<FolderInfo | undefined>(
    undefined
  )
  const [breadcrumbs, setBreadcrumbs] = useState<BreadcrumbItem[]>([
    { label: 'OneDrive' },
  ])
  const [folders, setFolders] = useState<FolderInfo[]>([])
  const [files, setFiles] = useState<FileInfo[]>([])
  const [selectedFileId, setSelectedFileId] = useState<string | null>(null)
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [newFileName, setNewFileName] = useState('')
  const [fileNameError, setFileNameError] = useState<string | null>(null)

  const loadFolderContents = useCallback(
    async (folder?: FolderInfo) => {
      setIsLoading(true)
      setError(null)

      try {
        const result = await cloudStorage.listFoldersAndFiles(folder)
        setFolders(result.folders)
        setFiles(result.files)
        setCurrentFolder(folder)
        setSelectedFileId(null)
      } catch (err) {
        setError(
          err instanceof Error ? err.message : 'Failed to load folder contents'
        )
      } finally {
        setIsLoading(false)
      }
    },
    [cloudStorage]
  )

  // Load initial folder listing when modal opens
  useEffect(() => {
    if (opened) {
      loadFolderContents(undefined)
    }
  }, [opened, loadFolderContents])

  const navigateToFolder = (folder: FolderInfo) => {
    loadFolderContents(folder)
    setBreadcrumbs([...breadcrumbs, { label: folder.name, path: folder.path }])
  }

  const navigateToBreadcrumb = (index: number) => {
    if (index === 0) {
      // Navigate to root
      loadFolderContents(undefined)
      setBreadcrumbs([{ label: 'OneDrive' }])
    } else {
      const targetBreadcrumb = breadcrumbs[index]
      // Find the folder from the breadcrumb path
      const targetPath = targetBreadcrumb.path
      if (targetPath) {
        // Create a FolderInfo from breadcrumb
        const targetFolder: FolderInfo = {
          id: '', // ID not needed for navigation
          name: targetBreadcrumb.label,
          path: targetPath,
        }
        loadFolderContents(targetFolder)
      }
      setBreadcrumbs(breadcrumbs.slice(0, index + 1))
    }
  }

  const navigateUp = () => {
    if (breadcrumbs.length > 1) {
      navigateToBreadcrumb(breadcrumbs.length - 2)
    }
  }

  const handleSelectFile = () => {
    const selectedFile = files.find(f => f.id === selectedFileId)
    if (selectedFile) {
      onSelectFile(selectedFile)
    }
  }

  const validateFileName = (name: string): string | null => {
    const fileNames = files.map(f => f.name)
    return syncService.validateSyncFileName(name, fileNames)
  }

  const handleFileNameChange = (value: string) => {
    setNewFileName(value)
    const error = validateFileName(value)
    setFileNameError(error)
  }

  const handleCreateFile = () => {
    const error = validateFileName(newFileName)
    if (error) {
      setFileNameError(error)
      return
    }

    const finalName = syncService.normalizeSyncFileName(newFileName)
    const finalPath = currentFolder
      ? `${currentFolder.path}/${finalName}`
      : `/${finalName}`

    const newFile: FileInfo = {
      id: '', // Will be generated by provider
      name: finalName,
      path: finalPath,
      isSharedWithMe: false,
    }

    setShowCreateModal(false)
    setNewFileName('')
    setFileNameError(null)
    onSelectFile(newFile)
  }

  const renderError = () => (
    <Alert
      icon={<IconAlertCircle size="1rem" />}
      title="Error"
      color="red"
      mb="md"
    >
      {error}
      <Button
        size="xs"
        variant="light"
        mt="sm"
        onClick={() => loadFolderContents()}
      >
        Retry
      </Button>
    </Alert>
  )

  const renderFolderBrowser = () => (
    <Stack gap="md">
      <Group justify="space-between">
        <Breadcrumbs>
          {breadcrumbs.map((breadcrumb, index) => (
            <Anchor
              key={index}
              onClick={() => navigateToBreadcrumb(index)}
              style={{ cursor: 'pointer' }}
            >
              {breadcrumb.label}
            </Anchor>
          ))}
        </Breadcrumbs>
        {breadcrumbs.length > 1 && (
          <ActionIcon variant="subtle" onClick={navigateUp} aria-label="Up">
            <IconArrowUp size="1rem" />
          </ActionIcon>
        )}
      </Group>

      {isLoading ? (
        <Group justify="center" p="xl">
          <Loader />
        </Group>
      ) : (
        <>
          {/* Folders and Files */}
          {folders.length === 0 && files.length === 0 ? (
            <Text c="dimmed" ta="center" p="xl">
              No items in this folder
            </Text>
          ) : (
            <Stack gap="xs">
              {/* Folders */}
              {folders.map(folder => (
                <Paper
                  key={folder.id}
                  p="md"
                  withBorder
                  role="button"
                  onClick={() => navigateToFolder(folder)}
                  style={{ cursor: 'pointer' }}
                >
                  <Group>
                    <IconFolder size="1.5rem" />
                    <Text flex={1}>{folder.name}</Text>
                    {folder.isSharedWithMe && (
                      <Badge
                        size="sm"
                        leftSection={<IconShare size="0.8rem" />}
                      >
                        Shared
                      </Badge>
                    )}
                  </Group>
                </Paper>
              ))}

              {/* Files */}
              <Radio.Group
                value={selectedFileId || ''}
                onChange={setSelectedFileId}
              >
                {files.map(file => (
                  <Paper key={file.id} p="md" withBorder>
                    <Group>
                      <Radio
                        value={file.id}
                        aria-label={file.name}
                        styles={{ radio: { cursor: 'pointer' } }}
                      />
                      <IconFile size="1.5rem" />
                      <Text flex={1}>{file.name}</Text>
                      {file.isSharedWithMe && (
                        <Badge
                          size="sm"
                          leftSection={<IconShare size="0.8rem" />}
                        >
                          Shared
                        </Badge>
                      )}
                    </Group>
                  </Paper>
                ))}
              </Radio.Group>
            </Stack>
          )}
        </>
      )}
    </Stack>
  )

  return (
    <>
      <Modal
        opened={opened}
        onClose={onClose}
        title="Select File"
        size="lg"
        closeOnEscape={!showCreateModal}
      >
        <Stack gap="md">
          {error && renderError()}
          {renderFolderBrowser()}

          <Group justify="flex-end" mt="md">
            <Button variant="subtle" onClick={onClose}>
              Cancel
            </Button>
            <Button
              variant="light"
              onClick={() => setShowCreateModal(true)}
              disabled={isLoading}
            >
              Create New File
            </Button>
            <Button
              onClick={handleSelectFile}
              disabled={!selectedFileId || isLoading}
            >
              Select File
            </Button>
          </Group>
        </Stack>
      </Modal>

      <Modal
        opened={showCreateModal}
        onClose={() => {
          setShowCreateModal(false)
          setNewFileName('')
          setFileNameError(null)
        }}
        title="Create New File"
        size="md"
      >
        <Stack gap="md">
          <TextInput
            label="File Name"
            placeholder="meal-plan-data"
            value={newFileName}
            onChange={e => handleFileNameChange(e.currentTarget.value)}
            error={fileNameError}
            description="Extension .json.gz will be added automatically"
            data-autofocus
          />

          <Group justify="flex-end" mt="md">
            <Button
              variant="subtle"
              onClick={() => {
                setShowCreateModal(false)
                setNewFileName('')
                setFileNameError(null)
              }}
            >
              Cancel
            </Button>
            <Button
              onClick={handleCreateFile}
              disabled={!!fileNameError || !newFileName.trim()}
            >
              Create
            </Button>
          </Group>
        </Stack>
      </Modal>
    </>
  )
}
