import { useState, useEffect, useCallback } from 'react'

import { useSyncContext } from '../contexts/SyncContext'
import { syncService } from '../services/syncService'

import type {
  FileInfo,
  FolderInfo,
} from '../utils/storage/ICloudStorageProvider'

interface BreadcrumbItem {
  label: string
  path?: string
}

interface UseFileSelectionModalParams {
  onSelectFile: (fileInfo: FileInfo) => void
}

export function useFileSelectionModal({
  onSelectFile,
}: UseFileSelectionModalParams) {
  const { listFoldersAndFiles } = useSyncContext()

  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [currentFolder, setCurrentFolder] = useState<FolderInfo | undefined>(
    undefined
  )
  const [breadcrumbs, setBreadcrumbs] = useState<BreadcrumbItem[]>([
    { label: 'OneDrive' },
  ])
  const [folders, setFolders] = useState<FolderInfo[]>([])
  const [files, setFiles] = useState<FileInfo[]>([])
  const [selectedFileId, setSelectedFileId] = useState<string | null>(null)
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [newFileName, setNewFileName] = useState('')
  const [fileNameError, setFileNameError] = useState<string | null>(null)

  const loadFolderContents = useCallback(
    async (folder?: FolderInfo) => {
      setIsLoading(true)
      setError(null)

      try {
        const result = await listFoldersAndFiles(folder)
        setFolders(result.folders)
        setFiles(result.files)
        setCurrentFolder(folder)
        setSelectedFileId(null)
      } catch (err) {
        setError(
          err instanceof Error ? err.message : 'Failed to load folder contents'
        )
      } finally {
        setIsLoading(false)
      }
    },
    [listFoldersAndFiles]
  )

  // Load initial folder listing on mount
  useEffect(() => {
    void loadFolderContents(undefined)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []) // Only run on mount

  const navigateToFolder = useCallback(
    (folder: FolderInfo) => {
      void loadFolderContents(folder)
      setBreadcrumbs(prev => [
        ...prev,
        { label: folder.name, path: folder.path },
      ])
    },
    [loadFolderContents]
  )

  const navigateToBreadcrumb = useCallback(
    (index: number) => {
      if (index === 0) {
        // Navigate to root
        void loadFolderContents(undefined)
        setBreadcrumbs([{ label: 'OneDrive' }])
      } else {
        const targetBreadcrumb = breadcrumbs[index]
        // Find the folder from the breadcrumb path
        const targetPath = targetBreadcrumb.path
        if (targetPath) {
          // Create a FolderInfo from breadcrumb
          const targetFolder: FolderInfo = {
            id: '', // ID not needed for navigation
            name: targetBreadcrumb.label,
            path: targetPath,
          }
          void loadFolderContents(targetFolder)
        }
        setBreadcrumbs(breadcrumbs.slice(0, index + 1))
      }
    },
    [breadcrumbs, loadFolderContents]
  )

  const navigateUp = useCallback(() => {
    if (breadcrumbs.length > 1) {
      navigateToBreadcrumb(breadcrumbs.length - 2)
    }
  }, [breadcrumbs.length, navigateToBreadcrumb])

  const handleSelectFile = useCallback(() => {
    const selectedFile = files.find(f => f.id === selectedFileId)
    if (selectedFile) {
      onSelectFile(selectedFile)
    }
  }, [files, selectedFileId, onSelectFile])

  const validateFileName = useCallback(
    (name: string): string | null => {
      const fileNames = files.map(f => f.name)
      return syncService.validateSyncFileName(name, fileNames)
    },
    [files]
  )

  const handleFileNameChange = useCallback(
    (value: string) => {
      setNewFileName(value)
      const error = validateFileName(value)
      setFileNameError(error)
    },
    [validateFileName]
  )

  const handleCreateFile = useCallback(() => {
    const error = validateFileName(newFileName)
    if (error) {
      setFileNameError(error)
      return
    }

    const finalName = syncService.normalizeSyncFileName(newFileName)
    const finalPath = currentFolder
      ? `${currentFolder.path}/${finalName}`
      : `/${finalName}`

    const newFile: FileInfo = {
      id: '', // Will be generated by provider
      name: finalName,
      path: finalPath,
      isSharedWithMe: false,
    }

    setShowCreateModal(false)
    setNewFileName('')
    setFileNameError(null)
    onSelectFile(newFile)
  }, [validateFileName, newFileName, currentFolder, onSelectFile])

  const closeCreateModal = useCallback(() => {
    setShowCreateModal(false)
    setNewFileName('')
    setFileNameError(null)
  }, [])

  return {
    // State
    isLoading,
    error,
    breadcrumbs,
    folders,
    files,
    selectedFileId,
    showCreateModal,
    newFileName,
    fileNameError,

    // Actions
    setSelectedFileId,
    setShowCreateModal,
    loadFolderContents,
    navigateToFolder,
    navigateToBreadcrumb,
    navigateUp,
    handleSelectFile,
    handleFileNameChange,
    handleCreateFile,
    closeCreateModal,
  }
}
